### ISSUE TITLE
Incorrect dates are displayed on the Timeline view.

### ISSUE THREAD

**Issue by jmegenealogy** [wikitree/wikitree-dynamic-tree#38] opened 2022-10-12 18:25 UTC
From [G2G](https://www.wikitree.com/g2g/1481431/wikitree-hacktoberfest-2022-bug-reports?show=1481784#a1481784):

> I'm not sure what constitutes a bug since I am not a programmer, but when using the timeline option the display does not appear to be correct. It displayed my husband's birthdate as 0000 (he's old, but not that old). Also, my three sons were displayed as if they were born in the 1960s, but they were born in the 1980s. My daughter displayed correctly in the 1980s (girl power?!) I could only figure out how to display my immediate family, parents, siblings, children, husbands, even my ex-husband who I don't believe is linked to me in the tree - just to the children.

> Or was I just using an older version of the Dynamic Tree? I am using Edge.

**Comment by MichalVasut** [comment] 2022-10-12 19:43
@jmegenealogy maybe some steps to reproduce the issue would be helpful.

**Comment by harrislineage** [comment] 2022-10-13 16:32
There is a current branch with extensive updates to the timeline that will be pulled soon. I am going to close this as "can't reproduce" for now and we can revisit on the next update if still applicable.

**Closed by harrislineage** 2022-10-13 16:32 UTC
Labels: bug
